sudo: required
dist: trusty

language: ruby
rvm:
  - 2.2.3

before_install:
  - sudo bash ./.travis/before_install.sh

before_script:
  - sudo bash ./.travis/before_script.sh

script:
  - bash ./.travis/script.sh
